/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteligenciaViralRouteImport } from './routes/inteligencia-viral'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteligenciaViralSpyAgentRouteImport } from './routes/inteligencia-viral.spy-agent'
import { Route as InteligenciaViralMisVideosRouteImport } from './routes/inteligencia-viral.mis-videos'
import { Route as InteligenciaViralBuscadorRouteImport } from './routes/inteligencia-viral.buscador'
import { Route as InteligenciaViralAnalizarPerfilRouteImport } from './routes/inteligencia-viral.analizar-perfil'
import { Route as ApiRecreateScriptRouteImport } from './routes/api.recreate-script'
import { Route as ApiEnhancePostRouteImport } from './routes/api.enhance-post'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaViralRoute = InteligenciaViralRouteImport.update({
  id: '/inteligencia-viral',
  path: '/inteligencia-viral',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaViralSpyAgentRoute =
  InteligenciaViralSpyAgentRouteImport.update({
    id: '/spy-agent',
    path: '/spy-agent',
    getParentRoute: () => InteligenciaViralRoute,
  } as any)
const InteligenciaViralMisVideosRoute =
  InteligenciaViralMisVideosRouteImport.update({
    id: '/mis-videos',
    path: '/mis-videos',
    getParentRoute: () => InteligenciaViralRoute,
  } as any)
const InteligenciaViralBuscadorRoute =
  InteligenciaViralBuscadorRouteImport.update({
    id: '/buscador',
    path: '/buscador',
    getParentRoute: () => InteligenciaViralRoute,
  } as any)
const InteligenciaViralAnalizarPerfilRoute =
  InteligenciaViralAnalizarPerfilRouteImport.update({
    id: '/analizar-perfil',
    path: '/analizar-perfil',
    getParentRoute: () => InteligenciaViralRoute,
  } as any)
const ApiRecreateScriptRoute = ApiRecreateScriptRouteImport.update({
  id: '/api/recreate-script',
  path: '/api/recreate-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhancePostRoute = ApiEnhancePostRouteImport.update({
  id: '/api/enhance-post',
  path: '/api/enhance-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/inteligencia-viral': typeof InteligenciaViralRouteWithChildren
  '/login': typeof LoginRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/recreate-script': typeof ApiRecreateScriptRoute
  '/inteligencia-viral/analizar-perfil': typeof InteligenciaViralAnalizarPerfilRoute
  '/inteligencia-viral/buscador': typeof InteligenciaViralBuscadorRoute
  '/inteligencia-viral/mis-videos': typeof InteligenciaViralMisVideosRoute
  '/inteligencia-viral/spy-agent': typeof InteligenciaViralSpyAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/inteligencia-viral': typeof InteligenciaViralRouteWithChildren
  '/login': typeof LoginRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/recreate-script': typeof ApiRecreateScriptRoute
  '/inteligencia-viral/analizar-perfil': typeof InteligenciaViralAnalizarPerfilRoute
  '/inteligencia-viral/buscador': typeof InteligenciaViralBuscadorRoute
  '/inteligencia-viral/mis-videos': typeof InteligenciaViralMisVideosRoute
  '/inteligencia-viral/spy-agent': typeof InteligenciaViralSpyAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/inteligencia-viral': typeof InteligenciaViralRouteWithChildren
  '/login': typeof LoginRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/recreate-script': typeof ApiRecreateScriptRoute
  '/inteligencia-viral/analizar-perfil': typeof InteligenciaViralAnalizarPerfilRoute
  '/inteligencia-viral/buscador': typeof InteligenciaViralBuscadorRoute
  '/inteligencia-viral/mis-videos': typeof InteligenciaViralMisVideosRoute
  '/inteligencia-viral/spy-agent': typeof InteligenciaViralSpyAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/inteligencia-viral'
    | '/login'
    | '/api/enhance-post'
    | '/api/recreate-script'
    | '/inteligencia-viral/analizar-perfil'
    | '/inteligencia-viral/buscador'
    | '/inteligencia-viral/mis-videos'
    | '/inteligencia-viral/spy-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/inteligencia-viral'
    | '/login'
    | '/api/enhance-post'
    | '/api/recreate-script'
    | '/inteligencia-viral/analizar-perfil'
    | '/inteligencia-viral/buscador'
    | '/inteligencia-viral/mis-videos'
    | '/inteligencia-viral/spy-agent'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/editor'
    | '/inteligencia-viral'
    | '/login'
    | '/api/enhance-post'
    | '/api/recreate-script'
    | '/inteligencia-viral/analizar-perfil'
    | '/inteligencia-viral/buscador'
    | '/inteligencia-viral/mis-videos'
    | '/inteligencia-viral/spy-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  InteligenciaViralRoute: typeof InteligenciaViralRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiEnhancePostRoute: typeof ApiEnhancePostRoute
  ApiRecreateScriptRoute: typeof ApiRecreateScriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-viral': {
      id: '/inteligencia-viral'
      path: '/inteligencia-viral'
      fullPath: '/inteligencia-viral'
      preLoaderRoute: typeof InteligenciaViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-viral/spy-agent': {
      id: '/inteligencia-viral/spy-agent'
      path: '/spy-agent'
      fullPath: '/inteligencia-viral/spy-agent'
      preLoaderRoute: typeof InteligenciaViralSpyAgentRouteImport
      parentRoute: typeof InteligenciaViralRoute
    }
    '/inteligencia-viral/mis-videos': {
      id: '/inteligencia-viral/mis-videos'
      path: '/mis-videos'
      fullPath: '/inteligencia-viral/mis-videos'
      preLoaderRoute: typeof InteligenciaViralMisVideosRouteImport
      parentRoute: typeof InteligenciaViralRoute
    }
    '/inteligencia-viral/buscador': {
      id: '/inteligencia-viral/buscador'
      path: '/buscador'
      fullPath: '/inteligencia-viral/buscador'
      preLoaderRoute: typeof InteligenciaViralBuscadorRouteImport
      parentRoute: typeof InteligenciaViralRoute
    }
    '/inteligencia-viral/analizar-perfil': {
      id: '/inteligencia-viral/analizar-perfil'
      path: '/analizar-perfil'
      fullPath: '/inteligencia-viral/analizar-perfil'
      preLoaderRoute: typeof InteligenciaViralAnalizarPerfilRouteImport
      parentRoute: typeof InteligenciaViralRoute
    }
    '/api/recreate-script': {
      id: '/api/recreate-script'
      path: '/api/recreate-script'
      fullPath: '/api/recreate-script'
      preLoaderRoute: typeof ApiRecreateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-post': {
      id: '/api/enhance-post'
      path: '/api/enhance-post'
      fullPath: '/api/enhance-post'
      preLoaderRoute: typeof ApiEnhancePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InteligenciaViralRouteChildren {
  InteligenciaViralAnalizarPerfilRoute: typeof InteligenciaViralAnalizarPerfilRoute
  InteligenciaViralBuscadorRoute: typeof InteligenciaViralBuscadorRoute
  InteligenciaViralMisVideosRoute: typeof InteligenciaViralMisVideosRoute
  InteligenciaViralSpyAgentRoute: typeof InteligenciaViralSpyAgentRoute
}

const InteligenciaViralRouteChildren: InteligenciaViralRouteChildren = {
  InteligenciaViralAnalizarPerfilRoute: InteligenciaViralAnalizarPerfilRoute,
  InteligenciaViralBuscadorRoute: InteligenciaViralBuscadorRoute,
  InteligenciaViralMisVideosRoute: InteligenciaViralMisVideosRoute,
  InteligenciaViralSpyAgentRoute: InteligenciaViralSpyAgentRoute,
}

const InteligenciaViralRouteWithChildren =
  InteligenciaViralRoute._addFileChildren(InteligenciaViralRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  InteligenciaViralRoute: InteligenciaViralRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiEnhancePostRoute: ApiEnhancePostRoute,
  ApiRecreateScriptRoute: ApiRecreateScriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
